"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MongoModel = exports.disconnect = exports.connect = exports.defineModel = void 0;
var schema_1 = require("./schema");
Object.defineProperty(exports, "defineModel", { enumerable: true, get: function () { return schema_1.defineModel; } });
var client_1 = require("./client");
Object.defineProperty(exports, "connect", { enumerable: true, get: function () { return client_1.connect; } });
Object.defineProperty(exports, "disconnect", { enumerable: true, get: function () { return client_1.disconnect; } });
var model_1 = require("./model");
Object.defineProperty(exports, "MongoModel", { enumerable: true, get: function () { return model_1.MongoModel; } });
